name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Mise à jour vers checkout@v4 pour la compatibilité avec Node 20

      - name: Set up Python
        uses: actions/setup-python@v5  # Mise à jour vers setup-python@v5 pour la compatibilité avec Node 20
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
